package com.solveria.core.iam.infrastructure.persistence.mapper;

import com.solveria.core.iam.domain.model.Role;
import com.solveria.core.iam.infrastructure.persistence.entity.RoleJpaEntityExample;

/**
 * EXAMPLE: Mapper between domain Role and JPA entity (Clean Architecture Pattern).
 *
 * <p><strong>⚠️ This is a REFERENCE IMPLEMENTATION.</strong> Not currently used in production.
 *
 * <p>Responsibilities:
 *
 * <ul>
 *   <li><strong>toDomain:</strong> Converts JPA entity → Domain model (for use cases)
 *   <li><strong>toEntity:</strong> Converts Domain model → JPA entity (for persistence)
 * </ul>
 *
 * <h3>Key Principle:</h3>
 *
 * <p>Domain models should <strong>NEVER</strong> know about JPA. The mapper is the translation
 * layer between the two worlds, living in the infrastructure layer.
 *
 * <h3>Usage in Adapter:</h3>
 *
 * <pre>{@code
 * @Component
 * public class RoleRepositoryAdapter implements RoleRepositoryPort {
 *     private final RoleJpaRepository jpaRepo;
 *     private final RoleJpaMapper mapper;
 *
 *     public Role findById(UUID id) {
 *         return jpaRepo.findById(id)
 *             .map(mapper::toDomain)
 *             .orElseThrow();
 *     }
 *
 *     public Role save(Role domain) {
 *         RoleJpaEntity entity = mapper.toEntity(domain);
 *         RoleJpaEntity saved = jpaRepo.save(entity);
 *         return mapper.toDomain(saved);
 *     }
 * }
 * }</pre>
 *
 * @see Role
 * @see RoleJpaEntityExample
 * @see <a href="../../../../../../adr/ADR-001-jpa-in-domain-technical-debt.md">ADR-001</a>
 */
public class RoleJpaMapperExample {

    /**
     * Converts JPA entity to pure domain model.
     *
     * @param entity JPA entity from database
     * @return Pure domain model for use cases
     */
    public Role toDomain(RoleJpaEntityExample entity) {
        if (entity == null) {
            return null;
        }

        // Create pure domain object (no JPA annotations)
        Role domain = new Role(entity.getName(), entity.getDescription());

        // Map ID from BaseEntity
        // domain.setId(entity.getId());  // Assuming domain has setId

        // Note: Complex relationships (users, permissions) would need recursive mapping
        // or lazy loading strategies depending on use case needs

        return domain;
    }

    /**
     * Converts pure domain model to JPA entity for persistence.
     *
     * @param domain Pure domain model from use cases
     * @return JPA entity ready for database
     */
    public RoleJpaEntityExample toEntity(Role domain) {
        if (domain == null) {
            return null;
        }

        // Create JPA entity (ID will be auto-generated by JPA)
        RoleJpaEntityExample entity =
                new RoleJpaEntityExample(domain.getName(), domain.getDescription());

        // Map collections if needed (usually done in separate methods)
        // entity.setPermissions(mapPermissions(domain.getPermissions()));

        return entity;
    }

    /**
     * Updates existing JPA entity with domain values (for updates).
     *
     * @param entity Existing JPA entity
     * @param domain Updated domain values
     */
    public void updateEntity(RoleJpaEntityExample entity, Role domain) {
        if (entity == null || domain == null) {
            return;
        }

        entity.setName(domain.getName());
        entity.setDescription(domain.getDescription());

        // Relationship updates would go here
    }
}
